builders:
  ecs_builder:
    import: "package:flutter_event_component_system_generator/flutter_event_component_system_generator.dart"
    builder_factories: ["ecsBuilder"]
    build_extensions: {".dart": [".ecs.g.dart"]}
    auto_apply: dependents
    build_to: source
