name: flutter_event_component_system
description: "A Flutter package for Event-Component-System state management"
issueTracker: https://github.com/FlameOfUdun/flutter_event_component_system/issues
repository: https://github.com/FlameOfUdun/flutter_event_component_system
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.6.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
