name: flutter_event_component_system_lints
description: Lints for the Flutter Event-Component-System package. Promotes clean architecture, testability, and includes visual debugging with Inspector
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ^8.0.0
  analyzer_plugin: ^0.13.0
  custom_lint_builder: ^0.8.0 