name: flutter_event_component_system_inspector
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  devtools_extensions: ^0.4.0
  devtools_app_shared: ^0.4.0
  vm_service: ^15.0.2
  graphview: ^1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
